# Generated by Django 3.2.13 on 2022-05-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220514_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='piece',
            field=models.CharField(default='', max_length=100, verbose_name='토큰조각'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=400, unique=True, verbose_name='토큰'),
        ),
    ]
